### PR TITLE
removed current notifications query limit

### LINKED ISSUE #1466: Notification Pill shouldn't stop at 10
**Is your feature request related to a problem? Please describe.**
If there are more than 10 Notifications, the Notification Pill will stop counting.
On the Beta, it displays more than 10 in the Pill.

**Describe the solution you'd like**
It should not stop counting at 10 Notifications or it should display 9+ in the Pill.

### PR DESCRIPTION
**Pull request by tobiasreinhard**
Removed query limit from latest notifications, fixed #1466

### CODE REVIEW

**Comment by jeyemwey** [comment]
May I ask for your motivation for this? Some users have hundreds and thousands of notifications which would severely slow down their performance (fetching and rendering). That's why I'd first look into other options before just removing the limit.

**Comment by MrKrisKrisu** [comment]
I understand the motivation behind it, I also sometimes have > 10 notifications and only see max. 10 pieces.

However, the programming of the notifications is not designed to load so many notifications, that would delay the loading extremely. (See the APIv1 implementation - the endpoint of it takes forever to load - Issue #647).

I would therefore close the PR until the performance of the query has been optimized. Sorry.

**Comment by tobiasreinhard** [comment]
Sorry, i messed up. I thought it only loads current notifications of a user, not all notifications at once.

**Comment by MrKrisKrisu** [comment]
I think the best way would be to add Pagination aroudn this and optimize the mapping with Eager Loading.

Thanks anyway for the PR! <3

**Pull request closed without merging**
