### PR TITLE
Revert "Underline username on leaderboard on hover"

### PR DESCRIPTION
**Pull request by jeyemwey**
Reverts Traewelling/traewelling#83

Build failed for some reasons? Maybe @MrKrisKrisu can take a look into that.

### CODE REVIEW

**Comment by MrKrisKrisu** [comment]
Thats strange. In the PullRequest I touched just SCSS and HTML. But the test throws a `Illuminate\Database\QueryException`. I don't think my PR is the reason for. 🤨

**Comment by jeyemwey** [comment]
I don't think so either, but I wonder why this issue happens now, since it did not occur on the last commits?

**Comment by MrKrisKrisu** [comment]
Screenshot 2020-08-21 at 13 11 30
I just tested locally, but cannot confirm the test results...

**Comment by MrKrisKrisu** [comment]
The error occurred in `database/seeds/UsersTableSeeder.php:16`. The factory for users doesn't look like there is a mechanism to check if the username is already given. So maybe the factory creates this situation exceptionally. 

Maybe @HerrLevin can look at these and fix his factory? I don't have any knowledge about Laravel factories. I generate my example data another way in Seeders...

**Comment by MrKrisKrisu** [comment]
I fixed the factory, which causes the exception *sometimes* in #85. So you can close this PR and merge the other one.

**Pull request closed without merging**
