### PR TITLE
:fire: Cleanup notification classes

### PR DESCRIPTION
**Pull request by MrKrisKrisu**

### CODE REVIEW

**Comment by MrKrisKrisu** [comment]
@jeyemwey I don't see any reason for the `via`-functions. Can you confirm me, that I can remove these?
Notifications work for me without.

**Comment by jeyemwey** [comment]
> I don't see any reason for the `via`-functions. Can you confirm me, that I can remove these? Notifications work for me without.

`via` is [part of the Laravel Notification Interface](https://laravel.com/docs/9.x/notifications#specifying-delivery-channels). I'm not sure how deleting the method might impact the delivery/saving of notifications. If you don't want to specify it every time, I'd suggest moving it to the BaseNotification class.

**Comment by MrKrisKrisu** [comment]
We don't have other broadcast channels registered, but yeah: We'll go the safe way and I added the function to the BaseController. :)

**Comment by jeyemwey** [comment]
> We don't have other broadcast channels registered

Yes we do, EmailVerification and PasswordReset emails are sent via a notification.

**Comment by MrKrisKrisu** [comment]
not important i guess. :D

**Pull request closed without merging**
