### PR TITLE
🎨 Create travel types enum

### PR DESCRIPTION
**Pull request by EventHorizon8**
I created two types of constants:
- TravelType - travel types, which user uses in interface,
- HafasTravelType - travel types from api.
When I read the code I noticed, that validations in controller must work only with values from filters in form, and I use only TravelType-s constants in validation in TransportController.php

### CODE REVIEW

**Comment by EventHorizon8** [comment]
@MrKrisKrisu could you help me will tests? Codacy has an error:
```
2021-05-05 17:05:35.318Z error [CodacyCoverageReporter] Invalid configuration: Either a project or account API token must be provided or available in an environment variable  - (CodacyCoverageReporter.scala:25)

 --> Failed!
```
 How can I restart tests or what can I do with this error?

**Comment by MrKrisKrisu** [comment]
@HerrLevin Can you please take over? You set this up and I have no idea about it.

**Comment by EventHorizon8** [comment]
> @HerrLevin Can you please take over? You set this up and I have no idea about it.

In these comments
https://github.com/Traewelling/traewelling/pull/281#issuecomment-832004297
https://github.com/Traewelling/traewelling/pull/281#issuecomment-832021722

I suggested to put TravelTypes into constants to use them easier, thats why I create with PR.

**Comment by EventHorizon8** [comment]
@MrKrisKrisu may be it will be better to open new pull request or you can restart tests?

**Comment by HerrLevin** [comment]
> @MrKrisKrisu may be it will be better to open new pull request or you can restart tests?

Running a codacy code coverage test will not work on a PR outside of the main repository because you don't have access rights to our API key. This is to be expected. All other tests seem to be working just fine. I'll have to verify them for myself on my local machine before merging but for now it's looking good.

**Review by MrKrisKrisu — APPROVED** [review]
Wow, thanks for your changes! This really improves the code structurally a lot. 

Since the test could not be done due to the missing coverage key, I tested your PR local. -> Works

**Pull request merged**
