### PR TITLE
Fixed a bug wherein a login would redirect to /notifications/latest.

### LINKED ISSUE #28: Login redirects to "/notifications/latest"
**Describe the bug**
After login, the user gets redirected to `/notifications/latest`. This results in the delivery of the corresponding JSON file. 

**To Reproduce**
1. Go to login page, unauthenticated.
2. Login with credentials (tested with mail login, not social)
4. you get served a JSON file.

**Expected behavior**
After login, the user gets redirected to his dashboard.

**Desktop (please complete the following information):**
 - OS: Debian 10 Buster
 - Browser: Mozilla Firefox
 - Version: `Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0`

**Additional context**
Commit: [1c55723227b1399d623ad3f4906420eebd8bb130](https://github.com/Traewelling/traewelling/commit/1c55723227b1399d623ad3f4906420eebd8bb130)

### PR DESCRIPTION
**Pull request by HerrLevin**
fetch() seems to pick up the 302 redirect to /dashboard and translates it to a 302-"request" to /notifications/latest while logging in.

"fixed" by only loading notifications on button-click.

Closes #28

### CODE REVIEW

**Comment by jeyemwey** [comment]
[AdminLTE seems to be broken right now](https://github.com/ColorlibHQ/AdminLTE/issues/2660). Your code LGTM, will re-run the tests and merge _soon_.

**Comment by REJack** [comment]
@jeyemwey AdminLTE dropped the nodejs 8 support since it's End-of-Life since 31.12.2019.

**Comment by HerrLevin** [comment]
> @jeyemwey AdminLTE dropped the nodejs 8 support since it's End-of-Life since 31.12.2019.

Thank you very much for the info. I've removed the workflows for nodejs 8 and now it's working. :)

**Comment by REJack** [comment]
No problem :D If you have other problems with AdminLTE feel free to mention me on an issue here.

**Pull request merged**
