### PR TITLE
:sparkles: add Co2 savings to profile view

### PR DESCRIPTION
**Pull request by tomizius**
I want to see how much co2 I've safed against driving by car with the train during my live.
I used following source https://www.quarks.de/umwelt/klimawandel/co2-rechner-fuer-auto-flugzeug-und-co/

Unfortunately it's not easy to calculate how much the user has been driven by ÖPNV or IC(E). So I used the factor 15 to calculate the value and divided it by 100.

### CODE REVIEW

**Review by HerrLevin — APPROVED** [review]

**Comment by MrKrisKrisu** [comment]
I am unsure whether I like this PR. On the one hand, I find an attribute more in the header of the profile is too much - especially in the mobile view. I also find the calculation of the saved CO2 too flat. The differences between bus, train, car, ... are not taken into account enough.

image

**Review by MrKrisKrisu — CHANGES_REQUESTED** [review]
I am unsure whether I like this PR. On the one hand, I find an attribute more in the header of the profile is too much - especially in the mobile view. I also find the calculation of the saved CO2 too flat. The differences between bus, train, car, ... are not taken into account enough.

image

**Comment by MrKrisKrisu** [comment]
belongs to discussion #2327

**Comment by MrKrisKrisu** [comment]
As there was no further interaction, I refer to discussion #2327 and close the PR for the time being.

**Pull request closed without merging**
