### PR TITLE
Fixed admin-graphs with JS-Magic. ✨

### PR DESCRIPTION
**Pull request by HerrLevin**

### CODE REVIEW

**Comment by jeyemwey** [comment]
So what exactly did you do?

**Comment by HerrLevin** [comment]
> So what exactly did you do?

I moved the datasets from data-tags into a script-tag, since chart.js seems to have problems with single datasets in data-tags.

**Comment by jeyemwey** [comment]
Does this work in prod already?

**Comment by HerrLevin** [comment]
Yes it does!

Levin Baumann

**Pull request merged**
