### PR TITLE
Create es.json

### PR DESCRIPTION
**Pull request by timoteosg**
Spanish translation

### CODE REVIEW

**Comment by MrKrisKrisu** [comment]
Oh, cool, thank you very much! :)
Is this PR ready to review? There are some english strings in your translations.

**Comment by timoteosg** [comment]
didn't mean to upload it yet, im still missing some translations

> Oh, cool, thank you very much! :) Is this PR ready to review? There are some english strings in your translations.

**Comment by MrKrisKrisu** [comment]
No problem - then just let me know when you're done or mark the PR as draft. :)
Untranslated strings - if this would apply to you - can be removed at the end, as of traewelling use english as fallback then.

**Review by MrKrisKrisu — APPROVED** [review]
I will merge your current work so that your work is not lost in case someone else wants to add Spanish. :)

**Comment by timoteosg** [comment]
> I will merge your current work so that your work is not lost in case someone else wants to add Spanish. :)

Great, I'll continue working on it at some point!

**Pull request merged**
