### PR TITLE
✨ type safety for db-rest access

### LINKED ISSUE #1527: New format for train departures and journeys
**Is your feature request related to a problem? Please describe.**
We're currently just forwarding the resultset of a [db-rest v5](https://github.com/derhuerst/db-rest/) request to the api. This way we (and our api consumers) are completely dependend on their changes.

**Describe the solution you'd like**
A custom format, mapping the results of db-rest (and possible future data providers) to a specific format (version) controlled by us. That way we are able to produce reliable results without any concern of the underlying data structure.

**Additional context**
https://github.com/public-transport/friendly-public-transport-format

### PR DESCRIPTION
**Pull request by HerrLevin**
adds layer of abstraction in front of db-rest, so that we're in control of the data format and can seamlessly update the data provider.

related to #1635

closes #1527

### CODE REVIEW

**Comment by HerrLevin** [comment]
This utilizes some DTOs I had left from the GPN-backend-project.

@MrKrisKrisu can you please annotate in the DTOs, which properties we should remove?

**Comment by jeyemwey** [comment]
Hi, https://github.com/Traewelling/traewelling/commit/d1b98e08b3c82814c780d39822869cd4c732cc8e has fixed the lock-file issue which was blocking the unit tests. Can you please rebase your branch against upstream? Then the CI can run and this PR can be checked.

**Comment by MrKrisKrisu** [comment]
I noticed this PR has been in a draft state for a while. Are you currently actively working on this? If not, would it be possible to close this PR for now and perhaps reopen it later when you're ready to proceed? This helps in maintaining a clearer overview of ongoing projects.

Thank you for your attention to this matter. 😊

**Comment by MrKrisKrisu** [comment]
Since there was no further interaction here, I'll close this PR. Feel free to open it up again when we start working on it again. :)

**Pull request closed without merging**
