### PR TITLE
✨ Drop PHP 8.0, implement Enums

### LINKED ISSUE #302: [PHP 8.1] Adjust the enums to the PHP standard
When PHP 8.1 is released we should delete this file and adjust the enums to the PHP standard:
https://github.com/Traewelling/traewelling/blob/develop/app/Enum/BasicEnum.php

### PR DESCRIPTION
**Pull request by MrKrisKrisu**
closes #302

### CODE REVIEW

**Comment by HerrLevin** [comment]
🥵🥵🥵

**Comment by MrKrisKrisu** [comment]
Wait until PHP 8.1 is released (+ a few days buffer).

@HerrLevin  Can you look over it already? (no need to approve, yet. I will probably change some small things).

**Comment by HerrLevin** [comment]
Since you removed the "ready for review" label: is this still working or do you need to fix sth?

**Comment by MrKrisKrisu** [comment]
need some fixes. I fucked up some mergeconflicts...

**Review by HerrLevin — APPROVED** [review]

**Pull request merged**
