### PR TITLE
:technologist: Add stock avatars for seeded users

### PR DESCRIPTION
**Pull request by MrKrisKrisu**
I've added some default avatars to the seeder, so we have some examples in our local development. In 20% of all cases, users doesn't get a profile picture, so we can see this case, too.

image

### CODE REVIEW

**Comment by MrKrisKrisu** [comment]
(Copyright disclaimer: All pictures are taken by myself and are published under the [LICENSE](https://github.com/Traewelling/traewelling/blob/develop/LICENSE) of traewelling after merging this PR)

**Comment by ChillLP** [comment]
If you need anymore images, holler at me, i have some in stock and im sure we can arrange a thing

**Comment by HerrLevin** [comment]
Is this only for dev purposes?

**Comment by MrKrisKrisu** [comment]
> Is this only for dev purposes?

yes.

**Review by HerrLevin — APPROVED** [review]

**Review by HerrLevin — APPROVED** [review]

**Pull request merged**
