### PR TITLE
:bug: Delete old notifications based on created_at

### PR DESCRIPTION
**Pull request by HerrLevin**

### CODE REVIEW

**Review by MrKrisKrisu — APPROVED** [review]

**Comment by MrKrisKrisu** [comment]
maybe also reduce the time from 6 to 2 months?

**Comment by MrKrisKrisu** [comment]
Or less. Maybe 14 days can ca enough because all notifications are "Adhoc notifications".

**Comment by HerrLevin** [comment]
> Or less. Maybe 14 days

Also for the already read notifications?

**Comment by MrKrisKrisu** [comment]
> Also for the already read notifications?

Yes, I think we can delete all notifications 14 days after created.

**Pull request merged**
