### PR TITLE
:children_crossing: Summarize daily stats

### LINKED ISSUE #1362: Aggregate Statistics for /stats/daily
**Is your feature request related to a problem? Please describe.**
I'd like to know how long I was on public transport in a day (time, distance, avg. speed).

**Describe the solution you'd like**
The view at /stats/daily is expanded to contain statistics with the aforementioned information. Common iconography is applied.

**Additional context**
It might be useful to move aggregate functions (i.e. from the profile view and the leaderboard) to a separate function so that changes are applied everywhere.

### PR DESCRIPTION
**Pull request by MrKrisKrisu**
fixes #1362

### CODE REVIEW

**Comment by MrKrisKrisu** [comment]
Screenshot 2023-02-11 at 22 34 16

**Comment by MrKrisKrisu** [comment]
@jeyemwey Mobile it does not look so nice. If you have an idea, just push it in. Otherwise... no idea.
Screenshot 2023-02-11 at 22 35 52

**Comment by jeyemwey** [comment]
My changes make the stats look like this now :)

  

https://user-images.githubusercontent.com/2796271/218334245-79b40898-e442-422a-b892-e0d415712e9a.mp4

**Comment by jeyemwey** [comment]
Oaaar daaaa habe ich ein wenig gefettfingert, und gerebased statt zu squashen. Hoopsie, kommt ned mehr vor :pinkyswear:

**Pull request merged**
