### PR TITLE
🐛  Fix /reports endpoint

### PR DESCRIPTION
**Pull request by HerrLevin**

### CODE REVIEW

**Comment by HerrLevin** [comment]
@Traewelling/api-consumer This PR contains a breaking change of the `/report` endpoint. The change will be breaking after 2024-08-17

**Comment by jheubuch** [comment]
Thanks :)

**Comment by marhei** [comment]
This will also fix #2551, thanks for the change!

**Comment by HerrLevin** [comment]
> This will also fix #2551, thanks for the change!

Sadly not completely. We still have `likes_enabled` in the user model.

**Pull request merged**
