### PR TITLE
[DRAFT][MOCKUP] :sparkles: Add more journey information

### PR DESCRIPTION
**Pull request by MrKrisKrisu**
image

### CODE REVIEW

**Comment by jeyemwey** [comment]
For the remarks thing, I will absolutely need the emoji mapping: https://github.com/jeyemwey/train-ics-converter/blob/a5c90746969c46ca3073b84e92a616cfe880f931/src/emojis.ts#L41

**Comment by jeyemwey** [comment]
fyi, I've added some more mappings: https://github.com/jeyemwey/train-ics-converter/commit/1e646ea2d37611054606b5b4c8dff071dde3d00e

**Comment by MrKrisKrisu** [comment]
> For the remarks thing, I will absolutely need the emoji mapping

Maybe we can split this emojis in a separate repository in an universal format like csv, json, whatever, so every language can parse this?

**Comment by MrKrisKrisu** [comment]
carriages merged in another pr

**Pull request closed without merging**
